
project:
  type: website
execute:
  freeze: auto
website:
  google-analytics: "GG-378MDZNVX4"
  title: "Andreas Varotsis"
  site-url: "https://andreasthinks.me"
  description: "Personal website for Andreas Varotsis"
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  draft-mode: unlinked
  navbar:
    left:
      - text: "home"
        file: index.qmd
      - text: "about"
        file: about.qmd
      - text: "talks & publications"
        file: recent_work.qmd
      - text: "teaching"
        file: slides/index.qmd
    right:
      - text: "{{< fa brands mastodon size=xl >}}" 
        href: https://fosstodon.org/@AndreasThinks
        rel: "me"
      - text: "{{< fa brands bluesky size=xl >}}" 
        href: https://bsky.app/profile/andreasthinks.me
      - text: "{{< fa brands twitter size=xl >}}" 
        href: https://twitter.com/AndreasThinks
      - text: "{{< fa brands github size=xl >}}" 
        href: https://github.com/AndreasThinks
      - text: "{{< fa brands linkedin size=xl >}}" 
        href: https://www.linkedin.com/in/avarotsis/
      - text: "{{< fa envelope size=xl >}}" 
        href: mailto:andreas.varotsis@gmail.com
      - text: "{{< fa rss size=xl >}}" 
        href: index.xml
format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
